# Generated by Django 4.2.1 on 2025-02-19 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rolls', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roll',
            name='telegram_id',
        ),
        migrations.RemoveField(
            model_name='roll',
            name='username',
        ),
    ]
