# Generated by Django 4.2.1 on 2025-02-25 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rolls', '0002_remove_roll_telegram_id_remove_roll_username'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='roll',
            options={'verbose_name': 'Ролл', 'verbose_name_plural': 'Роллы'},
        ),
    ]
