# Generated by Django 4.2.1 on 2025-02-25 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rolls', '0003_alter_roll_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roll',
            name='text',
            field=models.TextField(max_length=1024, verbose_name='Текст'),
        ),
    ]
