# Generated by Django 4.2.1 on 2025-03-11 04:43

from django.db import migrations, models
import web.db.model_mixins


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BotSettings',
            fields=[
                ('id', models.CharField(db_index=True, default=web.db.model_mixins.ulid_default, editable=False, max_length=26, primary_key=True, serialize=False, unique=True)),
                ('text_after_registration', models.TextField(max_length=4000, verbose_name='Текст после регистрации')),
                ('roll_buttons_text', models.TextField(verbose_name='Текст кнопки под роллом')),
            ],
            options={
                'verbose_name': 'Тексты бота',
                'verbose_name_plural': 'Тексты бота',
            },
        ),
    ]
